#!/usr/bin/env python3
"""Doxygen config file converter."""
# Copyright © 2023 OOTA, Masato
#
# This is published by CC0 1.0.
# For more information, see CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
# at https://creativecommons.org/publicdomain/zero/1.0/deed).

import argparse
import pathlib
import re

arg_parser = argparse.ArgumentParser(description='Convert to the doxygen config file for man.')
arg_parser.add_argument(
    '-i', '--input',
    dest = 'input_file',
    help = 'Input doxygen config filename',
    type = argparse.FileType('r'),
    default = 'serdes_turn.doxygen',
)
arg_parser.add_argument(
    '-o', '--output',
    dest = 'output_file',
    help = 'Output doxygen config filename',
    type = argparse.FileType('w'),
    default = 'serdes_turn_man.doxygen',
)
arg_parser.add_argument(
    '-s', '--source-dir',
    dest = 'source_dir',
    help = 'source directory',
    type = pathlib.Path,
    default = pathlib.Path(),
)
args = arg_parser.parse_args()

gen_man_re = re.compile('^ *GENERATE_MAN *=.*$')
gen_html_re = re.compile('^ *GENERATE_HTML *=.*$')
input_re = re.compile('^ *INPUT *=*$')

for line in args.input_file:
    line = gen_man_re.sub('GENERATE_MAN = YES', line)
    line = gen_html_re.sub('GENERATE_HTML = NO', line)
    line = input_re.sub('INPUT = {}'.format(args.source_dir), line)
    args.output_file.write(line)

