#!/usr/bin/env python3
"""Man file generator."""
# Copyright © 2023 OOTA, Masato
#
# This is published by CC0 1.0.
# For more information, see CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
# at https://creativecommons.org/publicdomain/zero/1.0/deed).

import argparse
import shutil
import subprocess

arg_parser = argparse.ArgumentParser(description='Generate the man files.')
arg_parser.add_argument(
    '-e', '--exe',
    dest = 'doxygen_exe',
    help = 'doxygen executable filename',
    default = '/usr/bin/doxygen',
)
arg_parser.add_argument(
    '-c', '--config',
    dest = 'config_file',
    help = 'doxygen config filename',
    default = 'serdes_turn_man.doxygen',
)
arg_parser.add_argument(
    '-v', '--verbose',
    dest = 'verbose',
    help = 'verbose mode',
    action = 'store_true',
    default = False,
)
arg_parser.add_argument(
    'output_filenames',
    nargs = '+',
    help = 'The output man filenames',
)
args = arg_parser.parse_args()

doxygen_out = None if args.verbose else subprocess.DEVNULL

ret = subprocess.run([args.doxygen_exe, args.config_file], stdout=doxygen_out)
ret.check_returncode()

for out_name in args.output_filenames:
    shutil.copyfile('man/man3/serdes_turn_deg.h.3', out_name)
